# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-16 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=128)),
                ('firstName', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=245, unique=True)),
            ],
        ),
    ]
